checks:
    javascript: true

build:
    nodes:
        analysis:
            environment:
                node:
                    version: 8.9.1
        tests: true
    environment:
        node: 8.9.1
    dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

    tests:
        override:
            -
                #command: 'istanbul cover --report clover test.js'
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'clover'
