version: "2"
services:
    node8:
        container_name: "nim_test0"
        build:
            context: .
            dockerfile: docker/Dockerfile-node8
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/app/
        ports:
            - "3003:3003"
        command: "npm test"
    node8-alpine:
        container_name: "nim_test1"
        build:
            context: .
            dockerfile: docker/Dockerfile-node8-alpine
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/app/
        ports:
            - "3001:3001"
        command: "npm test"
    node8.9:
        container_name: "nim_test2"
        build:
            context: .
            dockerfile: docker/Dockerfile-node8.9
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/app/
        ports:
            - "3002:3002"
        command: "npm test"
